### ISSUE TITLE
I  got into trouble when running vulnx

### ISSUE THREAD

**Issue by aditia13** [anouarbensaad/vulnx#32]
.:.        .:,                    
                   xM;           XK.                  
                  dx'            .lO.                 
                 do                ,0.                
             .c.lN'      ,  '.     .k0.:'             
              xMMk;d;''cOM0kWXl,',locMMX.             
              .NMK.   :WMMMMMMMx    dMMc              
               lMMO  lWMMMMMMMMMO. lMMO               
                cWMxxMMMMMMMMMMMMKlWMk                
                 .xWMMMMMMMMMMMMMMM0,                 
                   .,OMd,,,;0MMMO,.                   
             .l0O.VXVXOX.VXVX0MOVXVX.0Kd,             
            lWMMO0VXVX0OX.VXVXlVXVX.VXNMMO            
           .MMX;.N0VXVX00X.VXVXVX0.0M:.OMMl           
          .OXc  ,MMOVXVX0VX .VXVX00MMo  ,0X'          
          0x.  :XMMMkVXVX.XO.VXVXdMMMWo.  :X'         
         .d  'NMMMMMMkVXVX..VXVX0.XMMMMWl  ;c         
            'NNoMMMMMMxVXVXVXVXVX0.XMMk0Mc            
           .NMx OMMMMMMdVXVXVXlVXVX.NW.;MMc           
          :NMMd .NMMMMMMdVXVXdMd,,,,oc ;MMWx          
          .0MN,  'XMMMMMMoVXoMMMMMMWl   0MW,          
           .0.    .xWMMMMM:lMMMMMM0,     kc           
            ,O.     .:dOKXXXNKOxc.      do            
             '0c        -VulnX-       ,Ol             
               ;.                     :.   

    # Coded By Anouar Ben Saad - @anouarbensaad      
                                           
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 257, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='site.ostudioworks.com', port=80): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 571, in <module>
    detect_cms()
  File "/usr/share/vulnx/vulnx.py", line 134, in detect_cms
    lm_content = vxget(lm,headers)
  File "/usr/share/vulnx/common/vxrequest.py", line 51, in getrequest
    return get(url)
  File "/usr/share/vulnx/common/vxrequest.py", line 48, in get
    stream=True,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 492, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='sito.blabla.com', port=80): Read timed out. (read timeout=3)

**Comment by anouarbensaad** [comment]
Can you verify if the fix works?
