### ISSUE TITLE
Error execution 

### ISSUE THREAD

**Issue by tXambe** [anouarbensaad/vulnx#95]
Hello,

When I execute vulnx I have this error:

```
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 157, in <module>
    detection()
  File "/usr/share/vulnx/vulnx.py", line 113, in detection
    instance.instanciate()
  File "/usr/share/vulnx/modules/detector.py", line 140, in instanciate
    print ("{0} \u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212\u2212".format(W))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 8-51: ordinal not in range(256)


```

Can anyone help me?

A greeting and thanks

**Comment by josepresas93** [comment]
When I execute I have a next errors:

[vulnx_issue.txt](https://github.com/anouarbensaad/vulnx/files/7478290/vulnx_issue.txt)

Can anyone help me?
Thanks.
